import type { NativeAnalysisResult } from '../../modules/expo-speedgun';
import type { PitchResult } from '../types';

export function toPitchResult(raw: NativeAnalysisResult): PitchResult {
  if (raw.error) throw new Error(raw.error);

  const speedInfo = raw.speed_info || {};
  return {
    job_id: raw.job_id || `offline_${Date.now()}`,
    speed_info: {
      release_speed_kmh: speedInfo.release_speed_kmh,
      initial_speed_kmh: speedInfo.initial_speed_kmh,
      max_speed_kmh: speedInfo.max_speed_kmh,
      total_distance_m: speedInfo.total_distance_m,
      effective_distance_m: speedInfo.effective_distance_m,
      flight_time_s: speedInfo.flight_time_s,
      horizontal_break_cm: speedInfo.horizontal_break_cm,
      vertical_break_cm: speedInfo.vertical_break_cm,
      induced_vertical_break_cm: speedInfo.induced_vertical_break_cm,
      total_break_cm: speedInfo.total_break_cm,
      break_angle_deg: speedInfo.break_angle_deg,
      break_confidence: speedInfo.break_confidence,
      break_gravity_drop_cm: speedInfo.break_gravity_drop_cm,
      break_fit_r2: speedInfo.break_fit_r2,
      break_endpoint_source: speedInfo.break_endpoint_source,
      break_samples: speedInfo.break_samples,
      break_actual_sample_ratio: speedInfo.break_actual_sample_ratio,
      break_cm_per_px_x: speedInfo.break_cm_per_px_x,
      break_cm_per_px_y: speedInfo.break_cm_per_px_y,
      pitch_type: speedInfo.pitch_type,
      pitch_confidence: speedInfo.pitch_confidence,
      calculation_method: speedInfo.calculation_method,
      physics_clamped: speedInfo.physics_clamped,
      trajectory_quality_warning: speedInfo.trajectory_quality_warning,
      release_point: speedInfo.release_point,
      catch_point: speedInfo.catch_point,
      glove_point: speedInfo.glove_point,
      plate_x_norm: speedInfo.plate_x_norm,
      plate_y_norm: speedInfo.plate_y_norm,
      catch_point_confidence: speedInfo.catch_point_confidence,
      catch_point_source: speedInfo.catch_point_source,
      plate_fit_error_px: speedInfo.plate_fit_error_px,
      plate_extrapolated_frames: speedInfo.plate_extrapolated_frames,
      plate_zone: speedInfo.plate_zone,
      batter_height_m: speedInfo.batter_height_m,
      strike_zone_width_cm: speedInfo.strike_zone_width_cm,
      strike_zone_height_cm: speedInfo.strike_zone_height_cm,
      strike_zone_rule: speedInfo.strike_zone_rule,
      pitch_loc_x: speedInfo.pitch_loc_x,
      pitch_loc_y: speedInfo.pitch_loc_y,
      is_strike: speedInfo.is_strike,
      no_ball_detected: speedInfo.no_ball_detected,
      estimated_distance_m: speedInfo.estimated_distance_m,
      distance_source: speedInfo.distance_source,
      distance_warning: speedInfo.distance_warning,
      ttc_status: speedInfo.ttc_status,
      flight_time_source: speedInfo.flight_time_source,
      ttc_flight_time_s: speedInfo.ttc_flight_time_s,
      visual_flight_time_s: speedInfo.visual_flight_time_s,
      release_frame_idx: speedInfo.release_frame_idx,
      release_frame_source: speedInfo.release_frame_source,
      first_ball_frame_idx: speedInfo.first_ball_frame_idx,
      catch_frame_idx: speedInfo.catch_frame_idx,
      release_time_s: speedInfo.release_time_s,
      first_ball_time_s: speedInfo.first_ball_time_s,
      catch_time_s: speedInfo.catch_time_s,
    },
    overlay_url: raw.overlay_uri,
    overlay_uri: raw.overlay_uri,
    created_at: new Date().toISOString(),
    total_frames: raw.total_frames,
    fps: raw.fps,
    video_width: raw.video_width,
    video_height: raw.video_height,
    trajectory_count: raw.trajectory_count,
    trajectory_actual_count: raw.trajectory_actual_count,
    trajectory_synthetic_count: raw.trajectory_synthetic_count,
    yolo_frames_processed: raw.yolo_frames_processed,
    yolo_raw_detection_frames: raw.yolo_raw_detection_frames,
    yolo_total_detections: raw.yolo_total_detections,
    yolo_ball_in_frame_count: raw.yolo_ball_in_frame_count,
    source_fps: raw.source_fps,
    capture_fps: raw.capture_fps,
    effective_capture_fps: raw.effective_capture_fps,
    interpolation_factor: raw.interpolation_factor,
    trajectory_points_norm: raw.trajectory_points_norm,
    trajectory_samples: raw.trajectory_samples,
    trajectory_metadata: raw.trajectory_metadata,
  };
}
